pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // API 102 is currently published by libxposed as an official release AAR.
        ivy {
            url = uri('https://github.com/libxposed/api/releases/download')
            patternLayout {
                artifact('[revision]/[artifact]-[revision].[ext]')
            }
            metadataSources {
                artifact()
            }
            content {
                includeModule('io.github.libxposed', 'api')
            }
        }
    }
}

rootProject.name = 'rusted-fabric-android-xposed'
include ':module'
include ':bootstrap-core'
project(':bootstrap-core').projectDir = file('../bootstrap-core')
include ':mod-runtime'
project(':mod-runtime').projectDir = file('../mod-runtime')
include ':rusted-fabric-api-common'
project(':rusted-fabric-api-common').projectDir = file('../../rusted-fabric-api-common')
include ':patched-bootstrap'
project(':patched-bootstrap').projectDir = file('../patched-bootstrap')
include ':game-api-stubs'
project(':game-api-stubs').projectDir = file('../game-api-stubs')
include ':local-patcher-core'
project(':local-patcher-core').projectDir = file('../local-patcher-core')
