rootProject.name = 'rusted-fabric-loader'
include 'rusted-fabric-api'
include 'rusted-fabric-api-desktop'
include 'rusted-fabric-api-android'
include 'example-mod'
include 'portable-example-mod'
include 'android:apk-inspector'
include 'android:bootstrap-core'
include 'android:mod-runtime'
include 'android:local-patcher-core'
include 'android:local-patcher-cli'
