id=rw-android-1.15-code176-pending
packageName=com.corrodinggames.rts
versionCode=176
mappingFile=mappings.tiny
anchor.gameEngine=Lcom/corrodinggames/rts/gameFramework/l;
anchor.frameworkGameObject=Lcom/corrodinggames/rts/gameFramework/w;
anchor.unit=Lcom/corrodinggames/rts/game/units/am;
anchor.orderableUnit=Lcom/corrodinggames/rts/game/units/y;
anchor.customUnit=Lcom/corrodinggames/rts/game/units/custom/j;
anchor.customUnitMetadata=Lcom/corrodinggames/rts/game/units/custom/l;
anchor.factoryQueueManager=Lcom/corrodinggames/rts/game/units/d/k;
anchor.effectManager=Lcom/corrodinggames/rts/gameFramework/d/c;
anchor.pathfindingEngine=Lcom/corrodinggames/rts/gameFramework/k/l;
anchor.settingsEngine=Lcom/corrodinggames/rts/gameFramework/SettingsEngine;
