id=rw-android-1.15-code176-v1.0
matchPolicy=exact
packageName=com.corrodinggames.rts
versionName=1.15
versionCode=176
apkSha256=328f37106985a2ba424efec9ac312ede0395f3bac56e3d5db5d642dd6aecc04c
mappingFile=mappings.tiny
mappingFileSha256=7df59d61092a7665f023242b0221baf3ba5a3e8a3f2415bfd85a247070676d07
anchor.application=Lcom/corrodinggames/rts/appFramework/RWApplication;
anchor.introScreen=Lcom/corrodinggames/rts/appFramework/IntroScreen;
anchor.gameEngine=Lcom/corrodinggames/rts/gameFramework/k;
anchor.rustedWarfareGameEngine=Lcom/corrodinggames/rts/game/i;
anchor.frameworkGameObject=Lcom/corrodinggames/rts/gameFramework/ah;
anchor.unit=Lcom/corrodinggames/rts/game/units/ce;
anchor.orderableUnit=Lcom/corrodinggames/rts/game/units/bp;
anchor.customUnit=Lcom/corrodinggames/rts/game/units/custom/j;
anchor.customUnitMetadata=Lcom/corrodinggames/rts/game/units/custom/l;
anchor.factoryQueueManager=Lcom/corrodinggames/rts/game/units/d/r;
anchor.effectEngine=Lcom/corrodinggames/rts/gameFramework/d/c;
anchor.pathEngine=Lcom/corrodinggames/rts/gameFramework/k/k;
anchor.settingsEngine=Lcom/corrodinggames/rts/gameFramework/SettingsEngine;
hook.gameEngineInit.owner=com/corrodinggames/rts/game/i
hook.gameEngineInit.name=a
hook.gameEngineInit.descriptor=(Landroid/content/Context;)V
hook.gameEngineInit.named=init
hook.networkEngine.owner=com/corrodinggames/rts/gameFramework/j/ae
hook.networkConnection.owner=com/corrodinggames/rts/gameFramework/j/c
hook.networkPacket.owner=com/corrodinggames/rts/gameFramework/j/bi
hook.network.register=f(Lcom/corrodinggames/rts/gameFramework/j/c;)V
hook.network.serverInfo=d(Lcom/corrodinggames/rts/gameFramework/j/c;)V
hook.network.dispatch=a(Lcom/corrodinggames/rts/gameFramework/j/bi;)V
hook.network.reset=a(Z)V
hook.network.start=a(Lcom/corrodinggames/rts/gameFramework/j/c;Z)Z
hook.team.owner=com/corrodinggames/rts/game/p
hook.unit.owner=com/corrodinggames/rts/game/units/ce
hook.team.unregister=b(Lcom/corrodinggames/rts/game/units/ce;)V
hook.team.register=c(Lcom/corrodinggames/rts/game/units/ce;)V
hook.command.owner=com/corrodinggames/rts/gameFramework/e
hook.command.issue=h()V
